# 端口
server:
  port: 8001
# 应用名称
spring:
  application:
    name: HIKARI-DEMO
# 数据源
  datasource:
# 数据源1
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://xx.com/db_name1?characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
      username:
      password:
# Hikari连接池配置
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: hikari-demo-primary
# 数据源2
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://xx.com/db_name2?characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
      username:
      password:
# Hikari连接池配置
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: hikari-demo-secondary

# Mybatis
mybatis:
  primary:
    mapper-locations: classpath*:mybatis/mapper/primary/*.xml
  secondary:
    mapper-locations: classpath*:mybatis/mapper/secondary/*.xml

# 日志文件
logging:
  level:
    com.qishao: debug
    org.springframework: info
  file:
    name: ./log/hikari-demo
